#+startup: indent showall
#+title: README file for sesame loader
#+author: Jacek Grzebyta
#+date: <2016-06-01 Wed>
#+startup: showall

[[https://travis-ci.org/jgrzebyta/sesame-loader.svg?branch=master]]


* 1. What is that?

=Sesame-loader= provides command line tools for managing Eclipse RDF4J/Sesame repository.

** Current package version

#+name: get-version
#+begin_src shell :exports results :results output raw drawer
version=$(gawk '{match($0,/^ *:version \"(.*)\"/,mt);if (mt[0]!=""){print mt[1]} }' build.boot)
echo ${version}
#+end_src

#+RESULTS: get-version
:RESULTS:
0.1.3-SNAPSHOT
:END:

** All binnary releases
#+name: list-tags
#+begin_src shell :exports results :results output replace table
echo "Tag | Commit | Date "
git tag --format="%(refname:strip=2), %(objectname:short), %(committerdate)" --sort="-committerdate"
#+end_src

Table contains list of all binnary releases with commit and date of commit. The top record is the latest.

#+RESULTS: list-tags
|     Tag | Commit  | Date                           |
|   0.1.4 | ede649e | Wed Jun 29 10:49:10 2016 +0100 |
| 0.1.3.1 | 20dc78f | Tue Jun 7 16:49:38 2016 +0100  |
|   0.1.3 | 3bdb25f | Tue Jun 7 01:14:42 2016 +0100  |
|   0.1.2 | c9ac85d | Mon Jun 6 17:33:38 2016 +0100  |
|  v0.1.1 | 617f05c | Thu May 19 15:07:43 2016 +0100 |
|  v0.0.1 | 2fe4ef3 | Thu Apr 28 09:41:36 2016 +0100 |
|  v0.0.3 | bc1f8fe |                                |



* 2. List of commands
** triple.loader
Loads data into triple store.
This is implementation of method described in [article] (http://www.rivuli-development.com/further-reading/sesame-cookbook/loading-large-file-in-sesame-native/) published in Rivuli's *The Sesame Coocbook*.


#+begin_src shell :exports source
java -cp triple-loader-0.1.1-SNAPSHOT-standalone.jar triple.loader [options]
#+end_src

*** Options
    - --server URL, -s :: Sesame SPARQL endpoint URL. Default: http://localhost:8080/rdf4j-server                  
    - --repositiry NAME, -r :: Repository id. Default: test
    - --file FILE, -f :: Data file path                                       
    - --file-type TYPE, -t :: Data file type. One of: turtle, n3, nq, rdfxml, rdfa. Default: turtle
    - --context IRI, -c :: Context (graph name) of the dataset
    - --help, -h :: Help
** sparql
Executes SPARQL /query/ on data provided by /file/.  

#+begin_src sh :exports source
java -cp triple-loader-0.1.1-SNAPSHOT-standalone.jar sparql [options]
#+end_src

*** Options
    - --file FILE, -f :: Data file path 
    - --file-type TYPE, -t :: Declares type of data. Possible formats are listed [[#user-content-options][here]]
    - --query STRINGm -q :: Path to file with query or the query itself
    - --help, -h :: Help
* 3. Contacts
To contact with me please use *Issues* interface.
